### PR TITLE
reject if data_items are not unique

### PR DESCRIPTION
**Pull request by fonsecadeline**
Could be useful, I already had the case. This saves us time knowing problem does not come from gem source code.

### CODE REVIEW

**Review by braktar — APPROVED** [review]

**Review by senhalil — COMMENTED** [review]
I understand why we would want to have this but I am not sure if it is a good idea since the gem doesn't have such a limitation :/ don't know ¯\_(ツ)_/¯ i am conflicted.

**Comment by braktar** [comment]
I have the very same feeling

**Comment by fonsecadeline** [comment]
Unfortunately I do not remember what happened. I will write a test to make sure we return the right number of items at the end, even if there are repeated items.
If number of items returned is correct then we do not need this check.

I do not know how we arrived to this case in the first place.

**Comment by senhalil** [comment]
> I do not know how we arrived to this case in the first place.

It was an instance with errors from a "study" but I don't remember much more

**Comment by senhalil** [comment]
@fonsecadeline it looks like we abandoned this idea. Lets close this ticket if that is the case.

**Comment by fonsecadeline** [comment]
@senhalil can't rather we merge this ? Is this checked elsewhere?

**Comment by senhalil** [comment]
The conclusion I had from the discussion above (19 Jan) is that the gem doesn't have such a limitation and this check is not necessary, did I miss something?

**Comment by fonsecadeline** [comment]
@senhalil sorry, I had not read whole conversation again. In fact if data_items are not uniq then we do not return right number of items in result.

That is why I think it would be interesting to have this check within gem.

**Comment by senhalil** [comment]
@fonsecadeline  `we do not return right number of items in result` Do you mean the clustering gem returns incorrect number of items in the centroids or the result returned by optim-api? If it is the latter then the best place for this check (and what to do about it is optim-api), if it is the former (I am surprised that this is the case) then we should fix it because it is a bug.

**Comment by senhalil** [comment]
There are multiple points we do `delete` and re`insert` during clustering but all of them are done by "object"

**Comment by senhalil** [comment]
It turns out this is the bug ! array deletes "all items from `self` that are equal to `obj`" https://apidock.com/ruby/Array/delete
```ruby
irb(main):002:0> a = [[1],[1],[2]]
=> [[1], [1], [2]]
irb(main):003:0> a.delete(a[0])
=> [1]
irb(main):004:0> a
=> [[2]]
irb(main):005:0> 
```

**Comment by senhalil** [comment]
I am pleasantly surprised and after checking the code again I agree that this is the fastest way to prevent this issue. Eventually (if it is needed and we need to lift this limitation) we can add an internal unique tag to each item so that there are no exact duplicates and remove this tag at the end.

**Review by senhalil — APPROVED** [review]

**Comment by senhalil** [comment]
@fonsecadeline last question before we merge this. Do you agree that this cannot be a problem for realistic instances (except a weird VRP where all services are at one single point sent by the user)?

**Pull request merged**
